### PR TITLE
Add attr table to docs

### PR DESCRIPTION
**Pull request by DocOtak**
This is a first attempt at adding a "table" of what attributes are added to the output of each function.

### CODE REVIEW

**Comment by rcaneill** [comment]
That's awesome!
I guess that there should be a way so that _attr_table.rst would be generated automatically when building the doc? I never really used sphinx so I don't know all the possibilities.
Another point: the title for Content should look similar to Installation, which is not the case now.

**Comment by DocOtak** [comment]
Yes things can auto generate, in one of my other projects I have the sphinx config exec the generate table scripts. As hacky as it feels, it has never broken on me.

Any thoughts on what the table/list of attrs should look like? Earlier I had tried a giant table of everything and it didn't fit horizontally.

**Comment by rcaneill** [comment]
> Any thoughts on what the table/list of attrs should look like? Earlier I had tried a giant table of everything and it didn't fit horizontally.

I think that it is quite nicely rendered now, I like the list. Maybe would be good to add the unit after the name of the output, e.g.
```
specvol_first_derivatives_wrt_enthalpy

Has 2 outputs

v_SA_wrt_h [ (m^3/kg)(g/kg)^-1 ]

v_h [ (m^3/kg)(J/kg)^-1 ]
```
And replace the units 1 by "unitless".

2 minor points that I think would be good to change:
1. Add a column after `Has 1 output:`
2. Do not show the item `standard_name` if it is empty

**Comment by DocOtak** [comment]
Current state:

The readme was was pretty good, so I just straight included it in the sphinx docs as the intro.

I decided to add a bunch of notes at the top of the attrs list describing what is going on there. I think it is better to note on the page exactly what you will see in the attrs when you call these functions. e.g. I'm going to see ``{"units": "1"}`` and not ``{"units": "unitless"}`` The "dimensionless" unit of "1" is taken straight out of the SI manual so it is something that most scientists should at least be aware of, and it's very frequently encountered in CF.

The progress in the last few weeks/months has been awesome and I don't really want to block the release of 0.2.0 with a bunch of internal API docs.

If you think this is "good enough" we/I can start on the release machinery. We should announce to CF and xarray lists as well once this is released.

**Comment by rcaneill** [comment]
I added some commits with typos correction.

There is still the 'Content' section title that is not set properly (I don't know how to change this), cf https://github.com/DocOtak/gsw-xarray/issues/35#issuecomment-1062675842_
Apart from this, I think that it is ready for release!

**Review by rcaneill — APPROVED** [review]
Ready to release :)

**Pull request merged**
