### PR TITLE
Add pre commit

### PR DESCRIPTION
**Pull request by DocOtak**
So far I've only added black as a pre-commit hook. Eventually we'll probably add mypy and maybe a linter like flake8.

For this first round do we want isort or something like it?

### CODE REVIEW

**Comment by rcaneill** [comment]
Nice!
I am not sure that mypy would be essential for a project as small but why not. I never used it but I'll be happy to see how it is used if necessary.
flake8 and isort would also be great!

**Review by rcaneill — APPROVED** [review]
Seems good to me!
Have you tested that the black test fails if a file is not formatted correctly? Should work, but if you haven't tested it quickly, I think it is good to do it before merge

**Comment by DocOtak** [comment]
Just tried it, CI failed as expected (yay)

**Comment by DocOtak** [comment]
So I think the only thing left for our 0.2.0 release are some docs, I haven't had a chance to work on them since I made that test PR. Hopefully this weekend or next week for getting those a little more... useful.

Do you consider anything else blocking?

**Comment by rcaneill** [comment]
According to the milestone, the docs are the only thing left, and I don't see anything else blocking the release.
I you don't want / don't have time to write the docs, I can write all or a part of it, just let me know in #10 what you do and what I do

**Pull request merged**
