### PR TITLE
Add flake in pre-commit

### PR DESCRIPTION
**Pull request by rcaneill**

### CODE REVIEW

**Comment by DocOtak** [comment]
I've been switching all my other projects over to [ruff](https://github.com/astral-sh/ruff) and dropping almost all the other lint tools, ruff even has new support for black style reformatting of code. Basically all my work/office stuff is either ruff+black+mypy, or ruff+mypy if I've switched over to ruff formatting.

**Comment by rcaneill** [comment]
I didn't know ruff, I'll have a look

**Comment by rcaneill** [comment]
@DocOtak I am in favour to merge this PR, and keep the migration to ruff for later. Is that ok for you?

**Comment by rcaneill** [comment]
Closing, I added flake8 in https://github.com/DocOtak/gsw-xarray/pull/71

**Pull request closed without merging**
